### ISSUE TITLE
Problem with authentication

### ISSUE THREAD

**Issue by JanBN** [treyg/synology-photos-memories#10]
I have also problem with authentication, not sure what doing wrong. I do not run it in docker, and it returns me 400 bad request
I'm sure ip address, quick connect id is correct. 
![image](https://github.com/treyg/synology-photos-memories/assets/7447593/9c063abb-15e2-409b-895d-06bae4f33c10)

when I change ip address to just ip address point to nas from my local network it returns 403 forbidden

![image](https://github.com/treyg/synology-photos-memories/assets/7447593/4e964e12-1e10-4b96-a511-8d9494cb3dce)

Don't you know what I'm doing wrong ?
thank you

**Comment by treyg** [comment]
Hi @JanBN sorry for the late reply. Did you ever get this figured out?

**Comment by JanBN** [comment]
Thank you for the reply. No unfortunately I didn't solve it.

**Comment by treyg** [comment]
@JanBN So you are trying to just run this as a node app locally, not using docker? How are you setting your env variables? It looks like they aren't being read correctly. Also, do you have MFA set up on your NAS?
