### ISSUE TITLE
Feature request - Output photos information in json or xml format

### ISSUE THREAD

**Issue by edel79** [treyg/synology-photos-memories#2]
Hello,

I'm looking for a script able to reproduce the "remember" facebook feature, for photos stored on a Synology Nas, using Synology photo database and api : each day, display one photo taken exactly X year(s) from the current date.

Your script is what I found the more relevant to what I whish.

It already retrieve photo(s) url for a specific date, I would like to have the following information added to the output :
- Exif Date/Time
- URL of the different thumbnail photo size, if any set
- Photo location, if any set
- Digital camera used, if any set

All this information given on a text file using XML or JSON format.
For my need, the existing mail output part is not usefull.

Unfortunately I can't help the JS scripting part, but if you want help about formatting the output, I will be able to help, by providing samples.

Thanks in advance :)

**Comment by treyg** [comment]
@edel79 I'll look into seeing how difficult this might be. I'm guessing it wouldn't be too hard. There's actually a PR open right now to show the photos in the selected range/day on a web page, instead of/along with the email. Is that ultimately what you're looking to do?

**Comment by edel79** [comment]
Hello, no as I wish to use the data in another script.

I have taken a look at yours wich is quite simple in fact, enough to make me understand how it works.

So I think I will make my own covering my needs, in a language I know better (php).

But I still have another suggestion you can look at, quite simple : your script works with a single user private space photos. But some users (like me) use the shared space to store the photos. This is the same API logic, your simply have to call the "Syno.fototeam" entry point instead of "Syno.foto".
You could add a setting to set which space(s) user wants to use (private and/or public).
________________________________
De : Trey Gordon ***@***.***>
Envoyé : Sunday, September 3, 2023 2:05:31 AM
À : treyg/synology-photos-memories ***@***.***>
Cc : edel79 ***@***.***>; Mention ***@***.***>
Objet : Re: [treyg/synology-photos-memories] Feature request - Output photos information in json or xml format (Issue #2)


@edel79<https://github.com/edel79> I'll look into seeing how difficult this might be. I'm guessing it wouldn't be too hard. There's actually a PR open right now to show the photos in the selected range/day on a web page, instead of/along with the email. Is that ultimately what you're looking to do?

**Comment by treyg** [comment]
@edel79 Good idea! That should be simple enough to add. I'll look into it when I get some time. I'll close this issue out for now since you found a solution to the original suggestion.
