### ISSUE TITLE
Unable to authenticate (Cannot read properties of undefined reading sid)

### ISSUE THREAD

**Issue by julianCast** [treyg/synology-photos-memories#7]
Hi! Good project!

What am I doing wrong?
This is my `NAS_IP: 192-168-1-31.SECRET.direct.quickconnect.to:5001`.
I know that NAS IP works but I can't get pass the authentication.
I've also tried with `192.168.1.31:5001` but same result. `(Cannot read properties of undefined reading sid)`

![Sin título](https://github.com/treyg/synology-photos-memories/assets/559677/bf5926ca-ec1a-4d0a-8a12-b5d2e4013043)

![Sin título2](https://github.com/treyg/synology-photos-memories/assets/559677/baae9b4c-1d79-4ebb-adbc-7f136b1f4ab9)

**Comment by julianCast** [comment]
I have just realized my password contain something like: `123&456`. So the query header is only taking 123 Your authentication function is not encoding the password. Opened a PR https://github.com/treyg/synology-photos-memories/pull/9

**Comment by treyg** [comment]
Closing this after merging your PR. Thanks for looking into it!
